name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-x64:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup vcpkg cache
      uses: actions/cache@v6.1.0
      with:
        path: |
          ~/.cache/vcpkg
          ${{ github.workspace }}/vcpkg_installed
        key: ${{ runner.os }}-vcpkg-x64-${{ hashFiles('vcpkg.json') || 'static-v1' }} # или фиксированный ключ
        restore-keys: |
          ${{ runner.os }}-vcpkg-x64-

    - name: Install Boost via vcpkg
      run: |
        vcpkg install boost-system boost-program-options boost-filesystem --triplet x64-windows-static --x-install-root="${{ github.workspace }}/vcpkg_installed
  
    - name: Configure CMake
      run: >
        cmake -A x64 -S . -B ./build 
        -DCMAKE_GENERATOR_TOOLSET=v143 
        -D_WIN32_WINNT=0x0601 
        -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
        -DVCPKG_TARGET_TRIPLET=x64-windows-static

    - name: Build Release
      run: cmake --build ./build --config Release --target ALL_BUILD -j 6

    - name: Upload artifacts (x64)
      uses: actions/upload-artifact@v7
      with:
        name: pci-1716-binaries-x64
        path: |
          build/application/data-logger/Release/data-logger.exe
          build/application/data-converter/Release/data-converter.exe

  build-x86:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [Win32]
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup vcpkg cache
      uses: actions/cache@v6.1.0
      with:
        path: |
          ~/.cache/vcpkg
          ${{ github.workspace }}/vcpkg_installed
        key: ${{ runner.os }}-vcpkg-x86-${{ hashFiles('vcpkg.json') || 'static-v1' }} # или фиксированный ключ
        restore-keys: |
          ${{ runner.os }}-vcpkg-x86-

    - name: Install Boost via vcpkg
      run: |
        vcpkg install boost-system boost-program-options boost-filesystem --triplet x86-windows-static --x-install-root="${{ github.workspace }}/vcpkg_installed

    - name: Configure CMake
      run: >
        cmake -A Win32 -S . -B ./build 
        -DCMAKE_GENERATOR_TOOLSET=v143 
        -D_WIN32_WINNT=0x0601 
        -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
        -DVCPKG_TARGET_TRIPLET=x86-windows-static

    - name: Build Release
      run: cmake --build ./build --config Release --target ALL_BUILD -j 6

    - name: Upload artifacts (x86)
      uses: actions/upload-artifact@v7
      with:
        name: pci-1716-binaries-x86
        path: |
          build/application/data-logger/Release/data-logger.exe
          build/application/data-converter/Release/data-converter.exe

  release:
    needs: [build-x64, build-x86]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download artifacts (x64)
      uses: actions/download-artifact@v8
      with:
        name: pci-1716-binaries-x64
        path: binaries/x64

    - name: Download artifacts (x86)
      uses: actions/download-artifact@v8
      with:
        name: pci-1716-binaries-x86
        path: binaries/x86

    - name: Create Release
      uses: softprops/action-gh-release@v3
      with:
        files: |
          binaries/x64/*.exe
          binaries/x86/*.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
